OnlineShopping.WebApp/Models/Pager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShopping.WebApp.Models
{
    public class Pager
    {
        public Pager()
        {
        }
        public string SearchText { get; set; } = "";
        public string Controller { get; set; } = "";
        public string Action { get; set; } = "Index";

        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }

        public int StartRecord { get; private set; }
        public int EndRecord { get; private set; }



        public Pager(int totalItems, int page, int pageSize = 10)
        {

            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 2;
            int endPage = currentPage + 2;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 5)
                {
                    startPage = endPage - 4;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;

            StartRecord = (CurrentPage - 1) * PageSize + 1;
            EndRecord = StartRecord - 1 + PageSize;

        }

    }
}

OnlineShopping.WebApp/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineShopping.Utility;
using OnlineShopping.WebApp.Models;
using OnlineShopping.WebApp.Models.Dto;
using OnlineShopping.WebApp.Services.IServices;
using System.Security.Claims;

namespace OnlineShopping.WebApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            APIResponse response = await _authService.LoginAsync<APIResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, model.User.Email));
                identity.AddClaim(new Claim(ClaimTypes.Role, model.User.Role));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                HttpContext.Session.SetString(SD.SessionToken, model.Token);
                HttpContext.Session.SetString(SD.SessionUserId, model.User.Id.ToString());
                HttpContext.Session.SetString(SD.SessionUserRole, model.User.Role);
                HttpContext.Session.SetString(SD.SessionUserMail, model.User.Email);
                HttpContext.Session.SetString(SD.SessionEmail, model.User.Name);
                HttpContext.Session.SetString(SD.SessionUserPhoneNumber, model.User.PhoneNumber);
                HttpContext.Session.SetString(SD.SessionUserImage, model.User.ImageUrl);


                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
                return View(obj);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDTO obj)
        {
            APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
            if (result != null && result.IsSuccess)
            {
                return RedirectToAction("Login");
            }
            else
            {
                ModelState.AddModelError("CustomError", result.ErrorMessages.FirstOrDefault());
                return View(obj);
            }

        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken, "");
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

OnlineShopping.WebApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineShopping.Utility;
using OnlineShopping.WebApp.Models;
using OnlineShopping.WebApp.Models.Dto;
using OnlineShopping.WebApp.Services.IServices;
using System.Net.Mail;
using System.Net;
using System.Security.Claims;

namespace OnlineShopping.WebApp.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [Authorize]
        public async Task<IActionResult> CartIndex()
        {
            return View(await LoadCartDtoBasedOnLoggedInUser());
        }

        private async Task<CartDto> LoadCartDtoBasedOnLoggedInUser()
        {

            var userId = HttpContext.Session.GetString(SD.SessionUserId);
            APIResponse? response = await _cartService.GetAsync<APIResponse>(userId);
            if (response != null & response.IsSuccess)
            {
                CartDto cartDto = JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result));
                return cartDto;
            }
            return new CartDto();

        }



        public async Task<IActionResult> Remove(int cartDetailsId)
        {
            var userId = HttpContext.Session.GetString(SD.SessionUserId);

            APIResponse? response = await _cartService.CreateAsync<APIResponse>(cartDetailsId);
            if (response != null & response.IsSuccess)
            {
                TempData["success"] = "Cart updated successfully";
                return RedirectToAction(nameof(CartIndex));
            }
            return View();
        }







      




        public async Task<IActionResult> SubmitCart()

        {

            var emailId = HttpContext.Session.GetString(SD.SessionUserMail);
            var userId = HttpContext.Session.GetString(SD.SessionUserId);
            var name = HttpContext.Session.GetString(SD.SessionEmail);

            APIResponse? response = await _cartService.GetAsync<APIResponse>(userId);


            CartDto cartDto = JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result));

            string fromMail = "jayarambande01@gmail.com";

            string fromPassword = "pfvrbgxmtqbtqjpy";




            var s = "Hi, " + name + " Your Order has been Succesfully Placed.<br>" + "<p><b>YOUR ORDERS ARE : </b></p> ";

            var i = 1;

            double amount = 0;


            foreach (var item in cartDto.CartDetails)

            {

                s += i.ToString() + "<br>" + "Product Name : " + item.Product.ProductName + "<br>" + "Quantity : " + item.Count + "<br>" + "Price : " + (item.Product.Price * item.Count).ToString("c") + "<p>";

                i++;

                amount += item.Product.Price * item.Count;

            }


            s += "<h4> Total Amount = " + amount.ToString("c") + "</h4>" + "<p>" + "<p>" + "<h5>THANK YOU</h5>";

            MailMessage message = new MailMessage();

            message.From = new MailAddress(fromMail);

            message.Subject = "ORDER DETAILS";

            //message.To.Add(new MailAddress("198w1a0407@vrsec.ac.in"));
            message.To.Add(new MailAddress(emailId));

            message.Body = s;

            message.IsBodyHtml = true;


            var smtpClient = new SmtpClient("smtp.gmail.com")

            {

                Port = 587,

                Credentials = new NetworkCredential(fromMail, fromPassword),

                EnableSsl = true,

            };


            smtpClient.Send(message);

            TempData["success"] = "Order Placed Successfully";

            return RedirectToAction("Index", "Home");


        }
    }
}

OnlineShopping.WebApp/Views/Shared/_Layout.cshtml
@using OnlineShopping.Utility
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShopping.WebApp</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShopping.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShopping.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        @if (httpAcc.HttpContext.Session.GetString(SD.SessionToken) != null && httpAcc.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
                        {


                            @if (httpAcc.HttpContext.Session.GetString(SD.SessionUserRole).ToString() == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="IndexCategory">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="IndexProduct">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserManager" asp-action="IndexUsers">UserManager</a>
                                </li>


                            }
                            

                            <li class="nav-item">
                                <a class="nav-link  text-dark" asp-area="" asp-controller="Cart" asp-action="CartIndex">
                                    &nbsp; <i class="bi bi-cart"></i>&nbsp;
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-dark" asp-area="" asp-controller="Home" asp-action="Profile">
                                    &nbsp; <i class="bi bi-person-fill"></i>&nbsp;
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>




                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineShopping.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineShopping.WebApp/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 1000,
            timerProgressBar: true
        })
        </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 1000,
            timerProgressBar: true
        })
    </script>
}

OnlineShopping.WebApp/Views/Shared/_Pager.cshtml
@model Pager




<div class="container btn-group" style="background-color:black; border-radius: 25px; height:45px;">




    <div class="col-4 p-0 justify-content-end mt-1">
        <form asp-controller="@Model.Controller" asp-action="@Model.Action">
            <span class="btn-group">
                <input class="form-control" type="text" name="SearchText"
                       value="@Model.SearchText" placeholder="Search Key">



                <input name="pageSize" type="hidden" value="@Model.PageSize" />



                <input class="p-1 ml-2 btn btn-sm btn-info" type="submit" value="Search" />
            </span>
        </form>
    </div>




    <div class="col-2 btn-group justify-content-end">
        <span class="col-7 mt-2 p-0">
            Rows Per Page
        </span>
        <span class="col-5 p-1">



            <select class="form-control" id="pageSelector" asp-items="@ViewBag.PageSizes"
                    onchange="ChangePageSize(this,'@Model.SearchText');">
            </select>



        </span>
    </div>




    <div class="col-6 btn-group container mt-1 justify-content-end">
        @if (Model.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">



                @if (Model.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-pg="1"
                           asp-route-SearchText="@Model.SearchText" asp-route-pageSize="@Model.PageSize">First</a>
                    </li>
                    <li>
                        <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action"
                           asp-route-pg="@(Model.CurrentPage - 1)"
                           asp-route-SearchText="@Model.SearchText" asp-route-pageSize="@Model.PageSize">Previous</a>
                    </li>
                }
                @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
                {
                    <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-pg="@pge"
                           asp-route-SearchText="@Model.SearchText" asp-route-pageSize="@Model.PageSize"> @pge </a>
                    </li>



                }
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action"
                           asp-route-SearchText="@Model.SearchText" asp-route-pg="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize">Next</a>
                    </li>
                    <li>
                        <a class="page-link" asp-controller="@Model.Controller" asp-action="@Model.Action"
                           asp-route-SearchText="@Model.SearchText" asp-route-pg="@(Model.TotalPages)" asp-route-pageSize="@Model.PageSize">Last</a>
                    </li>
                }
            </ul>
        }




    </div>



</div>



<div class="clearfix">
    <p></p>
</div>



<script>
    function ChangePageSize(obj, searchtext) {
        window.location.href = "/@Model.Controller/@Model.Action" + "?pageSize=" + obj.value + "&SearchText=" + searchtext;
    }
</script>